### ISSUE TITLE
RuntimeError: memory format option is only supported by strided tensors.

### ISSUE THREAD

**Issue by chandagrover** [hywang66/mmist#3]
Hi,

I am getting the below error on executing example.sh. Please help to fix it.

 RuntimeError: memory format option is only supported by strided tensors.

**Comment by hywang66** [comment]
Please provide more details so we can help. Like the error line number, screenshots, etc.

**Comment by chandagrover** [comment]
Below is the error, I am getting:

Setting up PyTorch plugin "bias_act_plugin"... Done.
Traceback (most recent call last):
  File "/home/phdcs2/Hard_Disk/Projects/T2I/mmist/gen_style_reps.py", line 110, in <module>
    stylegan, ws = model_bridge.load_stylegan3_model_with_ws(
  File "/home/abc/Hard_Disk/Projects/T2I/mmist/model_bridge.py", line 118, in load_stylegan3_model_with_ws
    ws = G.mapping(z, None, truncation_psi=1, truncation_cutoff=None, update_emas=False)
  File "/home/abc/Hard_Disk/Projects/T2I/mmist/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/abc/Hard_Disk/Projects/T2I/mmist/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "<string>", line 151, in forward
  File "/home/abc/Hard_Disk/Projects/T2I/mmist/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/abc/Hard_Disk/Projects/T2I/mmist/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "<string>", line 100, in forward
  File "/home/abc/Hard_Disk/Projects/T2I/mmist/stylegan3/torch_utils/ops/bias_act.py", line 85, in bias_act
    return _bias_act_cuda(dim=dim, act=act, alpha=alpha, gain=gain, clamp=clamp).apply(x, b)
  File "/home/abc/Hard_Disk/Projects/T2I/mmist/venv/lib/python3.9/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/abc/Hard_Disk/Projects/T2I/mmist/stylegan3/torch_utils/ops/bias_act.py", line 150, in forward
    y = _plugin.bias_act(x, b, _null_tensor, _null_tensor, _null_tensor, 0, dim, spec.cuda_idx, alpha, gain, clamp)
RuntimeError: memory format option is only supported by strided tensors
0it [00:00, ?it/s]
Setting up PyTorch plugin "bias_act_plugin"... Done.
Traceback (most recent call last):
  File "/home/abc/Hard_Disk/Projects/T2I/mmist/gen_style_reps.py", line 110, in <module>
    stylegan, ws = model_bridge.load_stylegan3_model_with_ws(
  File "/home/abc/Hard_Disk/Projects/T2I/mmist/model_bridge.py", line 118, in load_stylegan3_model_with_ws
    ws = G.mapping(z, None, truncation_psi=1, truncation_cutoff=None, update_emas=False)
  File "/home/abc/Hard_Disk/Projects/T2I/mmist/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/abc/Hard_Disk/Projects/T2I/mmist/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "<string>", line 151, in forward
  File "/home/abc/Hard_Disk/Projects/T2I/mmist/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/abc/Hard_Disk/Projects/T2I/mmist/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "<string>", line 100, in forward
  File "/home/abc/Hard_Disk/Projects/T2I/mmist/stylegan3/torch_utils/ops/bias_act.py", line 85, in bias_act
    return _bias_act_cuda(dim=dim, act=act, alpha=alpha, gain=gain, clamp=clamp).apply(x, b)
  File "/home/abc/Hard_Disk/Projects/T2I/mmist/venv/lib/python3.9/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/abc/Hard_Disk/Projects/T2I/mmist/stylegan3/torch_utils/ops/bias_act.py", line 150, in forward
    y = _plugin.bias_act(x, b, _null_tensor, _null_tensor, _null_tensor, 0, dim, spec.cuda_idx, alpha, gain, clamp)
RuntimeError: memory format option is only supported by strided tensors
0it [00:00, ?it/s]

**Comment by chandagrover** [comment]
Resolved. The code ran successfully.
Thank You for responding in so short time.
